### ISSUE TITLE
DbCmd GenerateEntities: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Becold** [Apps72/Dev.Data#39]
Hi,

I would like to generate my entities with the Range data annotation and for that, I am using this (simplified) command on my db: 
`DbCmd GenerateEntities -cs="Server=(localdb)\MyServer;Database=MyDatabase;" --provider=SqlServer --Namespace="MyProject.MyPackage.Entities" --Validations=Range`

But sadly, I got this error message : "Object reference not set to an instance of an object."

I am using the lastest version (4.3.0.1).

Could you check this please ?
Thanks.

**Comment by Becold** [comment]
The bug might be related to a view I created recently.

**Comment by dvoituron** [comment]
Hello,
Can you give me more details?
I tried to reproduce this problem, and even with a View, there is no bug.

Can you give me the TrackTrace and more context?

**Comment by Becold** [comment]
Sadly, the stack trace does not give much informations :

![image](https://user-images.githubusercontent.com/12863317/105759130-5bf90180-5f50-11eb-8aa9-246d27a7831c.png)

I could reproduce the bug with this view : 
```sql
CREATE VIEW [Order]
AS
 SELECT  [UserId],
         SUM([Amount]) AS [SumAmount]
    FROM [OrderLine]
GROUP BY [OrderLineId]
```

OrderLine.Amount is of type **DECIMAL(18,0)**.
![image](https://user-images.githubusercontent.com/12863317/105759970-6a93e880-5f51-11eb-9c1a-1b10f87e227a.png)

With this view, Order.SumAmount seems to be of type **DECIMAL(38,0)** in SSMS.
![image](https://user-images.githubusercontent.com/12863317/105759771-1e48a880-5f51-11eb-8b0e-50dc9316bc39.png)

I hope this helps you.

**Comment by dvoituron** [comment]
Indeed, that's the SumAmount range... probably too large for my C# objects.
I'll fix that quickly.

Thanks

**Comment by dvoituron** [comment]
Problem fixed... a new NuGet package (and tool) is piblished.
