### ISSUE TITLE
cmd.ExecuteTable<(Tuple)> does not map correctly columns data to tuple.

### ISSUE THREAD

**Issue by OniryxRomainMarbaix** [Apps72/Dev.Data#45]
Hello Denis :-)

I found out the cmd.ExecuteTable<(Tuple)> does not map correctly columns data to tuple.
On version 4.1.1

Example C# code:
```c#
using (var cmd = GetDatabaseCommand())
{
    cmd.TagWith("MyTag");
    cmd.CommandText = "SELECT [Id], [FirstName] FROM [Users]";
    var result = cmd.ExecuteTable<(int Id, string FirstName)>();
    System.Diagnostics.Debug.Assert(result.Count() == 1); // 1 user found: Ok
    System.Diagnostics.Debug.Assert(result.First().Id == 1); // Id is not the one expected: The assertion fails
}
```

**Comment by dvoituron** [comment]
Hello. 
Thanks for your feedback. I’ll check that. 
what the current result (an exception)?

**Comment by dvoituron** [comment]
After my initial research, I think that named `Tuple` objects forget the property names after the compilation process.

For example, this code...
```csharp
public void Main() {
    var data = MyMethod<(int Id, string Name)>();
    var x = data.Id;
    var y = data.Name;
}

T MyMethod<T>()
{
    return default(T);
}
```

... is compiled to this code. **We can see that the properties `Id` and `Name` are not included** (but replaced by `Item1` and `Item2`).
```csharp
public void Main()
{
    ValueTuple<int, string> valueTuple = MyMethod<ValueTuple<int, string>>();
    int item = valueTuple.Item1;
    string item2 = valueTuple.Item2;
}

private T MyMethod<T>()
{
    return default(T);
}
```

In this case, I can't use reflection to fill in the properties correctly.
I have to find another solution.
